CREATE TABLE T_USER
(
    ID INT PRIMARY KEY,
    EMAIL VARCHAR(64) NOT NULL,
    PASSWORD VARCHAR(256) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP
);
CREATE UNIQUE INDEX T_USER_EMAIL_UINDEX ON T_USER (EMAIL);
COMMENT ON COLUMN T_USER.EMAIL IS '登录邮箱';
COMMENT ON COLUMN T_USER.PASSWORD IS '登录密码';
COMMENT ON COLUMN T_USER.CREATED_AT IS '创建时间';
COMMENT ON COLUMN T_USER.UPDATED_AT IS '修改时间';

CREATE SEQUENCE SEQ_USER
  MINVALUE 1
  NOMAXVALUE
  INCREMENT BY 1
  START WITH 1
  NOCACHE;