CREATE TABLE SERVER
(
    ID VARCHAR(64) PRIMARY KEY NOT NULL,
    HOST VARCHAR(32) NOT NULL,
    PORT INT NOT NULL,
    INIT_AT TIMESTAMP NOT NULL,
    ACTIVE_AT TIMESTAMP NOT NULL
);
COMMENT ON COLUMN SERVER.HOST IS '主机地址';
COMMENT ON COLUMN SERVER.PORT IS '主机端口';
COMMENT ON COLUMN SERVER.INIT_AT IS '初始化时间';
COMMENT ON COLUMN SERVER.ACTIVE_AT IS '最后活跃时间';