CREATE TABLE APP
(
    ID INT PRIMARY KEY,
    NAME VARCHAR(64) NOT NULL,
    PROFILE VARCHAR(64) NOT NULL,
    DESCRIPTION VARCHAR(1024) NOT NULL,
    TOKEN VARCHAR(64),
    IP_LIMIT VARCHAR(1024),
    V INT NOT NULL,
    CONTENT CLOB,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    USERS VARCHAR(512)
);
CREATE UNIQUE INDEX APP_NAME_PROFILE_UINDEX ON APP (NAME, PROFILE);
CREATE INDEX APP_CREATED_AT_INDEX ON APP (CREATED_AT);
CREATE INDEX APP_UPDATED_AT_INDEX ON APP (UPDATED_AT);
COMMENT ON COLUMN APP.NAME IS '应用名称';
COMMENT ON COLUMN APP.PROFILE IS '应用环境';
COMMENT ON COLUMN APP.DESCRIPTION IS '应用描述';
COMMENT ON COLUMN APP.TOKEN IS '访问令牌';
COMMENT ON COLUMN APP.IP_LIMIT IS '可访问 IP';
COMMENT ON COLUMN APP.V IS '应用版本';
COMMENT ON COLUMN APP.CONTENT IS '应用配置内容';
COMMENT ON COLUMN APP.CREATED_AT IS '创建时间';
COMMENT ON COLUMN APP.UPDATED_AT IS '修改时间';
COMMENT ON COLUMN APP.USERS IS '应用所属用户';

CREATE SEQUENCE SEQ_APP
  MINVALUE 1
  NOMAXVALUE
  INCREMENT BY 1
  START WITH 1
  NOCACHE;